---

language: node_js
node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=cc1aa496ded9df19571a4613901de40a469e6b268cd734e6a151d7f09549444e

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
